#!/bin/bash
# Indodax Automatic Trading Tools
# Creator by Hasanal Bulkiah 
# FB: https://fb.me/root.florienzh
# GITHUB: https://github.com/florienzh4x

# HARAP DIBACA ISINYA SEBELUM ANDA MENJALANKAN SCRIPT INI
# JANGAN HAPUS APAPUN YANG ADA DI FOLDER INI (PENTING!!!)

# API KEY & SECRET KEY BISA DIDAPATKAN DI LINK https://indodax.com/trade_api
# !!!! IMPORTANT !!!!
# JANGAN LUPA UNTUK CENTANG PERMISSION TRADE
# !!!!!!!!!!!!!!!!!!!!

API_KEY=''
SECRET_KEY=''

# INFO TRADE OPTION (DEFAULT: TRADE_OPTION=''
# trade option adalah pengaturan untuk trading yang dilakukan
# jika trade option diisi dengan 'auto' maka trading akan dilakukan berulang 
# TRADE_OPTION=''
# jika dikosongkan maka trading yang dilakukan akan berhenti jika sudah take profit (trading 1 kali)
# diharuskan menggunakan pengaturan statis untuk option 'auto' agar tidak selalu mengisi form input di script
TRADE_OPTION=''

# pengaturan untuk balance idr yang mau digunakan untuk trading (IDR) (DEFAULT: 10000)
# isi pengaturan ini jika ingin balance yang dikeluarkan berupa statis (tidak berubah)
# kosongkan jika ingin mengisi pada form input saat script dijalankan
# NOTE: EXCLUDE FEE
TRADE_AMOUNT=''

# pengaturan untuk target profit yang diinginkan dalam persen (%) (CONTOH: TARGET_PROFIT='5'
# isi pengaturan ini jika target profit yang diinginkan berupa statis (tidak berubah)
# kosongkan jika ingin mengisi pada form input saat script dijalankan
# target profit dihitung dengan hasil rupiah coin yang dibeli + target profit
# rupiah coin yang dibeli + target profit (sell)
TARGET_PROFIT=''

# OPTION FEE (default: on)
# option ini digunakan untuk menghitung jumlah fee yang dikeluarkan
# jika option ini 'on' maka perhitungan target profit nya akan ditambahkan jumlah fee
# rumus (INCLUDE_FEE='on'
# contoh: (25.000.000 x 0.09) + 100.000 + 10.000 = 2.360.000 (jika sudah aset sudah mencapai total maka akan dijual)
# jika option ini 'off' maka perhitungan profit hanya akan mengambil jumlah coin yang dibeli
# rumus (INCLUDE_FEE='on'
# contoh: (25.000.000 x 0.09) + 100.000 = 2.350.000 (jika sudah aset sudah mencapai total maka akan dijual)
# option ini digunakan untuk memaksimalkan profit yang ditargetkan
INCLUDE_FEE='on'

TAPI='https://indodax.com/tapi'
API='https://indodax.com/api'